# Generated by Django 6.0.4 on 2026-04-29 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='querylog',
            name='category',
            field=models.CharField(choices=[('Single Integral', 'Single Integral'), ('Double Integral', 'Double Integral'), ('Beta Function', 'Beta Function')], default='Single Integral', max_length=50),
        ),
        migrations.AddField(
            model_name='querylog',
            name='is_correct',
            field=models.BooleanField(default=True),
        ),
    ]
