# Generated by Django 6.0.4 on 2026-04-29 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0002_querylog_category_querylog_is_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='querylog',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Easy', max_length=20),
        ),
    ]
